version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/client-server/Dockerfile
        env_file:
            - docker/client-server/.env
        ports:
            - "8080:8080"
